// File generated by FlutterFire CLI (customized for Android only)
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'This app is configured only for Android. Web is not supported.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'This app is configured only for Android platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFOBipTJ3vh1SrpJwvYxjnUhAAUYehIps',
    appId: '1:332395752763:android:d5eb888bb607a2c6c71b1e',
    messagingSenderId: '332395752763',
    projectId: 'pomori-2498d',
    storageBucket: 'pomori-2498d.firebasestorage.app',
  );

}